# Generated by Django 4.1.7 on 2023-08-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=256)),
                ("reg_no", models.PositiveIntegerField(unique=True)),
                ("net_asset", models.BigIntegerField(null=True)),
                ("cancel_nav", models.IntegerField(null=True)),
                (
                    "annual_efficiency",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                ("investment_manager", models.CharField(max_length=256, null=True)),
                ("ins_inv_no", models.IntegerField(null=True)),
                ("ret_inv_no", models.IntegerField(null=True)),
            ],
        ),
    ]
